#metadata(
  (
    title: "Kernel Level 2",
    description: "Writeup for Kernel Level 2",
    date: "2026-01-01",
    order: 2,
    draft: true,
  ),
)<frontmatter>
#import "../../../../typst-theme.c.typ": project
#show: project



#table(
  columns: (auto, 1fr),
  inset: 10pt,
  align: (right, left),
  [*Title*], [Kernel Logging and Secret Strings],
  [*Date*], [2025-12-30],
  [*Description*], [Using kernel logging (dmesg) to find or verify the results of interacting with a kernel module.],
)

= Babykernel Level 2

== Introduction

Similar to level 1, this challenge focuses on secret string verification within a kernel module.

== Vulnerability Analysis

The module compares the user-provided string with an internal secret. If they match, it logs the success (and possibly the flag) to the kernel buffer.

== Exploitation Steps

=== 1. Submitting the Secret
```bash
echo -n "hghlqjzerhxumnnf" > /proc/pwncollege
```

=== 2. Checking Kernel Logs
The `dmesg` command is used to view the output generated by `printk` within the kernel module.

```bash
dmesg | tail
```

